// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end.Data;

namespace back_end.Migrations
{
    [DbContext(typeof(LibrotecaContext))]
    partial class LibrotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("back_end.Models.FechaLectura", b =>
                {
                    b.Property<int>("IdFechaLectura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CantidadLeidas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeLectura")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdFechaLectura");

                    b.ToTable("FechaLectura");
                });

            modelBuilder.Entity("back_end.Models.InteresUsuario", b =>
                {
                    b.Property<int>("IdInteresUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Interes1")
                        .HasColumnType("int");

                    b.Property<int>("Interes2")
                        .HasColumnType("int");

                    b.Property<int>("Interes3")
                        .HasColumnType("int");

                    b.HasKey("IdInteresUsuario");

                    b.ToTable("InteresUsuario");
                });

            modelBuilder.Entity("back_end.Models.Intereses", b =>
                {
                    b.Property<int>("IdInteres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInteres");

                    b.ToTable("Intereses");
                });

            modelBuilder.Entity("back_end.Models.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AcnoLibro")
                        .HasColumnType("int");

                    b.Property<string>("AutorLibro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneroLibro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenLibro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreLibro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Paginas")
                        .HasColumnType("int");

                    b.Property<string>("Resegna")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLibro");

                    b.ToTable("Libro");
                });

            modelBuilder.Entity("back_end.Models.LibroUsuario", b =>
                {
                    b.Property<int>("IdLibroUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdLibro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdLibroUsuario");

                    b.ToTable("LibroUsuario");
                });

            modelBuilder.Entity("back_end.Models.ProgresoLectura", b =>
                {
                    b.Property<int>("IdProgresoLectura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("PaginasLeidas")
                        .HasColumnType("int");

                    b.HasKey("IdProgresoLectura");

                    b.ToTable("ProgresoLectura");
                });

            modelBuilder.Entity("back_end.Models.ProgresoLibros", b =>
                {
                    b.Property<int>("IdProgeso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdLibro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("PaginasAvance")
                        .HasColumnType("int");

                    b.HasKey("IdProgeso");

                    b.ToTable("ProgresoLibros");
                });

            modelBuilder.Entity("back_end.Models.PuntuacionLibro", b =>
                {
                    b.Property<int>("IdPuntuacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ComentarioLibro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLibro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.HasKey("IdPuntuacion");

                    b.ToTable("PuntuacionLibro");
                });

            modelBuilder.Entity("back_end.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaveUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Presentacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
